server-ip: 49.233.12.156
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server-ip}:3306/view_admin?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Best9Luck!
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
  redis:
    host: ${server-ip}
    port: 7963
    password: Best9Luck!
  cloud:
    nacos:
      discovery:
        server-addr: ${server-ip}:8848
logging:
  file:
    name: /var/log/view/view-admin.log
  pattern:
    rolling-file-name: /var/log/view/view-admin.%d{yyyy-MM-dd}-%i.gz
