server:
  port: 8085
spring:
  application:
    name: view-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/view_admin?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Best9Luck!
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 7963
    password: Best9Luck!
    subscribe:
      topic:
mybatis-plus:
  type-aliases-package: com.unisys.aos.view.admin.entity, com.unisys.aos.view.security.entity
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    com.unisys.aos.view: debug
  file:
    max-history: 30
    max-size: 10MB
    name: ./logs/view-admin.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID:- } --- [%thread] %-45.45logger{44} : %msg%n"
    rolling-file-name: view-admin.%d{yyyy-MM-dd}-%i.gz
jwt:
  enabled: true
  secret: Rum%>J]_@!DzALL0no3)^.0d
  accessTokenExpiration: 3000000
  refreshTokenExpiration: 86400000
  header: Authorization
  usernameHeader: UserId
  useDefaultController: true
  permitLoginUserURI:
    - /view/refresh-token
    - /view/logout
    - /view/logout-test
    - /view/admin/permit-all/functions
    - /view/admin/permit-all/user-setting
    - /view/admin/permit-all/user-profile
    - /view/admin/permit-all/role-profile
  permitAllURI:
    - /view/login-test
  test-token: WishAllTheBest!

