-- interface database DML Sql
DROP DATABASE IF EXISTS `aodbinterface`;
CREATE DATABASE `aodbinterface`;
USE aodbinterface;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `coutmsgs`;
CREATE TABLE `coutmsgs`
(
  `COUTMSGS_ID`               bigint(20) NOT NULL AUTO_INCREMENT,
  `COUTMSGS_CLOB_MSG`         MEDIUMTEXT,
  `COUTMSGS_DATE_INSERTED`    datetime NOT NULL,
  `COUTMSGS_DATE_SENT`        datetime,
  `ROUTINGID`                 VARCHAR(23) NOT NULL,
  `COUTMSGS_TRUEFALS_GROUP`   TINYINT DEFAULT 0 NOT NULL,
  `COUTMSGS_NO_MESSAGES`      TINYINT,
  `COUTMSGS_GROUP_ORDER`      TINYINT,
  `COUTMSGS_GROUP_ID`         SMALLINT,
  `COUTMSGS_FINAL_GROUP_IND`  TINYINT DEFAULT 0 NOT NULL,
  `COUTMSGS_ACK_REQD`         TINYINT DEFAULT 0 NOT NULL,
  `COUTMSGS_ACK_RESEND_TIMES` TINYINT DEFAULT 0 NOT NULL,
  `COUTMSGS_ACK_DATE_RECV`    datetime,
  `COUTMSGS_ENCRYPT`          TINYINT DEFAULT 0 NOT NULL,
  `COUTMSGS_ERROR`            TINYINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`COUTMSGS_ID`)
) ENGINE=InnoDB DEFAULT charSET=utf8mb4;


-- Create table
DROP TABLE IF EXISTS `cminmsgs`;
CREATE TABLE `cminmsgs`
(
  `CMINMSGS_ID`                  bigint(20) NOT NULL AUTO_INCREMENT,
  `CMINMSGS_CLOB_MSG`            MEDIUMTEXT NOT NULL,
  `CMINMSGS_DATE_RECEIVED`       datetime,
  `CMINMSGS_DATE_PROCESSED`      datetime,
  `CMINMSGS_SUBSYSTEM_NAME`      VARCHAR(4),
  `CMINMSGS_SUBSYSTEM_SEQUENCE`  MEDIUMINT,
  `CMINMSGS_SUBSYSTEM_DATE_SENT` datetime,
  `CMINMSGS_SUBSYSTEM_SUBTYPE`   VARCHAR(4),
  `CMINMSGS_SUBSYSTEM_TYPE`      VARCHAR(4),
  `CMINMSGS_STATUS`              VARCHAR(20),
  PRIMARY KEY (`CMINMSGS_ID`)
) ENGINE=InnoDB DEFAULT charSET=utf8mb4;
