server-ip: localhost
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server-ip}:3306/view?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Best9Luck!
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
  rabbitmq:
    host: ${server-ip}
    port: 5672
    username: viewuser
    password: viewpassword
    virtual-host: /view
    listener:
      simple:
        acknowledge-mode: manual
        #并发消费者初始化值
        concurrency: 1
        #并发消费者的最大值
        max-concurrency: 1
        #每个消费者每次监听时可拉取处理的消息数量
        prefetch: 1
  redis:
    host: ${server-ip}
    port: 7963
    password: Best9Luck!
  redisson:
    file: classpath:redisson-localhost.yml
    cloud:
      nacos:
        discovery:
          server-addr: ${server-ip}:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
