spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.12.156:3306/aodbinterface?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Best9Luck!
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
  rabbitmq:
    host: 49.233.12.156
    port: 5672
    username: viewuser
    password: viewpassword
    virtual-host: /view
  redis:
    host: 49.233.12.156
    port: 7963
    password: Best9Luck!
  redisson:
    file: classpath:redisson-liujie_cloud.yml
  cloud:
    nacos:
      discovery:
        server-addr: 49.233.12.156:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: /var/log/view/view-aodb-interface.log
  pattern:
    rolling-file-name: /var/log/view/view-aodb-interface.%d{yyyy-MM-dd}-%i.gz
