package com.unisys.aos.view.viewentity.entity.reference;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.unisys.aos.view.common.util.ThreadLocalDateUtil;
import com.unisys.aos.view.viewentity.config.ReferenceProperties;
import org.springframework.data.annotation.Transient;

import javax.annotation.Generated;
import javax.annotation.Resource;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * The <b>RdmsAirbridge</b> class is a POJO entity that represents the Airbridge Code
 * for reference data in message.
 * It is automatically generated by MyBatisGenerator.
 * The reference data in message definition can be referred to the section 3 of
 * the document SIS_AODB_RMS.doc.
 *
 * @author Zhang Wenqiang
 * @since 2020/10/21 23:50
 */
public class RdmsAirbridge implements Serializable {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private static final long serialVersionUID = 1L;
    @Transient
    public Date inspire;
    @Transient
    public Date expire;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String airbridgeCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String description;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String localDescription;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal maxHeight;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String terminalCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Boolean supportA380;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String associatedStands;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String associatedGates;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Byte armNumber;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long inspireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long expireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date createTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date updateTime;
    @Resource
    @Transient
    private ReferenceProperties referenceProperties;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAirbridgeCode() {
        return airbridgeCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAirbridgeCode(String airbridgeCode) {
        this.airbridgeCode = airbridgeCode == null ? null : airbridgeCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDescription() {
        return description;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getLocalDescription() {
        return localDescription;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setLocalDescription(String localDescription) {
        this.localDescription = localDescription == null ? null : localDescription.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getMaxHeight() {
        return maxHeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxHeight(BigDecimal maxHeight) {
        this.maxHeight = maxHeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getTerminalCode() {
        return terminalCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setTerminalCode(String terminalCode) {
        this.terminalCode = terminalCode == null ? null : terminalCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Boolean getSupportA380() {
        return supportA380;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setSupportA380(Boolean supportA380) {
        this.supportA380 = supportA380;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAssociatedStands() {
        return associatedStands;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAssociatedStands(String associatedStands) {
        this.associatedStands = associatedStands == null ? null : associatedStands.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAssociatedGates() {
        return associatedGates;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAssociatedGates(String associatedGates) {
        this.associatedGates = associatedGates == null ? null : associatedGates.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Byte getArmNumber() {
        return armNumber;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setArmNumber(Byte armNumber) {
        this.armNumber = armNumber;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getInspireTime() {
        return inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setInspireTime(Long inspireTime) {
        this.inspireTime = inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getExpireTime() {
        return expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getUpdateTime() {
        return updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getInspire() {
        if (null == inspireTime) {
            inspire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultInspireTime());
        } else {
            inspire = ThreadLocalDateUtil.timestampToDate(inspireTime);
        }
        return inspire;
    }

    public Date getExpire() {
        if (null == expireTime) {
            expire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultExpireTime());
        } else {
            expire = ThreadLocalDateUtil.timestampToDate(expireTime);
        }
        return expire;
    }

    @Override
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", airbridgeCode=").append(airbridgeCode);
        sb.append(", description=").append(description);
        sb.append(", localDescription=").append(localDescription);
        sb.append(", maxHeight=").append(maxHeight);
        sb.append(", terminalCode=").append(terminalCode);
        sb.append(", supportA380=").append(supportA380);
        sb.append(", associatedStands=").append(associatedStands);
        sb.append(", associatedGates=").append(associatedGates);
        sb.append(", armNumber=").append(armNumber);
        sb.append(", inspireTime=").append(inspireTime);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RdmsAirbridge)) return false;
        RdmsAirbridge that = (RdmsAirbridge) o;
        return Objects.equals(getAirbridgeCode(), that.getAirbridgeCode()) &&
                Objects.equals(getDescription(), that.getDescription()) &&
                Objects.equals(getLocalDescription(), that.getLocalDescription()) &&
                Objects.equals(getMaxHeight(), that.getMaxHeight()) &&
                Objects.equals(getTerminalCode(), that.getTerminalCode()) &&
                Objects.equals(getSupportA380(), that.getSupportA380()) &&
                Objects.equals(getAssociatedStands(), that.getAssociatedStands()) &&
                Objects.equals(getAssociatedGates(), that.getAssociatedGates()) &&
                Objects.equals(getArmNumber(), that.getArmNumber()) &&
                Objects.equals(getInspireTime(), that.getInspireTime()) &&
                Objects.equals(getExpireTime(), that.getExpireTime());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAirbridgeCode(), getDescription(), getLocalDescription(), getMaxHeight(), getTerminalCode(), getSupportA380(), getAssociatedStands(), getAssociatedGates(), getArmNumber(), getInspireTime(), getExpireTime());
    }


    /***
     * Get the identity of entity.
     * @return identity of entity
     */
    @JsonIgnore
    public String getIdentity() {
        return airbridgeCode + inspireTime + expireTime;
    }
}