package com.unisys.aos.view.viewentity.entity.reference;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.unisys.aos.view.common.util.ThreadLocalDateUtil;
import com.unisys.aos.view.viewentity.config.ReferenceProperties;
import org.springframework.data.annotation.Transient;

import javax.annotation.Generated;
import javax.annotation.Resource;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * The <b>RdmsAirline</b> class is a POJO entity that represents the Airline Code
 * for reference data in message.
 * It is automatically generated by MyBatisGenerator.
 * The reference data in message definition can be referred to the section 3 of
 * the document SIS_AODB_RMS.doc.
 *
 * @author Zhang Wenqiang
 * @since 2020/10/21 23:50
 */
public class RdmsAirline implements Serializable {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private static final long serialVersionUID = 1L;
    @Transient
    public Date inspire;
    @Transient
    public Date expire;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String iataOperatorCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String icaoOperatorCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String description;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String localDescription;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String countryCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String defaultTerminal;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String defaultTerminalMvin;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String defaultTerminalFlin;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String operatorGroups;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String airlineCategory;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long inspireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long expireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date createTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date updateTime;
    @Resource
    @Transient
    private ReferenceProperties referenceProperties;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getIataOperatorCode() {
        return iataOperatorCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIataOperatorCode(String iataOperatorCode) {
        this.iataOperatorCode = iataOperatorCode == null ? null : iataOperatorCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getIcaoOperatorCode() {
        return icaoOperatorCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIcaoOperatorCode(String icaoOperatorCode) {
        this.icaoOperatorCode = icaoOperatorCode == null ? null : icaoOperatorCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDescription() {
        return description;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getLocalDescription() {
        return localDescription;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setLocalDescription(String localDescription) {
        this.localDescription = localDescription == null ? null : localDescription.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getCountryCode() {
        return countryCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDefaultTerminal() {
        return defaultTerminal;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDefaultTerminal(String defaultTerminal) {
        this.defaultTerminal = defaultTerminal == null ? null : defaultTerminal.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDefaultTerminalMvin() {
        return defaultTerminalMvin;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDefaultTerminalMvin(String defaultTerminalMvin) {
        this.defaultTerminalMvin = defaultTerminalMvin == null ? null : defaultTerminalMvin.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDefaultTerminalFlin() {
        return defaultTerminalFlin;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDefaultTerminalFlin(String defaultTerminalFlin) {
        this.defaultTerminalFlin = defaultTerminalFlin == null ? null : defaultTerminalFlin.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getOperatorGroups() {
        return operatorGroups;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setOperatorGroups(String operatorGroups) {
        this.operatorGroups = operatorGroups == null ? null : operatorGroups.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAirlineCategory() {
        return airlineCategory;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAirlineCategory(String airlineCategory) {
        this.airlineCategory = airlineCategory == null ? null : airlineCategory.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getInspireTime() {
        return inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setInspireTime(Long inspireTime) {
        this.inspireTime = inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getExpireTime() {
        return expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getUpdateTime() {
        return updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getInspire() {
        if (null == inspireTime) {
            inspire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultInspireTime());
        } else {
            inspire = ThreadLocalDateUtil.timestampToDate(inspireTime);
        }
        return inspire;
    }

    public Date getExpire() {
        if (null == expireTime) {
            expire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultExpireTime());
        } else {
            expire = ThreadLocalDateUtil.timestampToDate(expireTime);
        }
        return expire;
    }

    @Override
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", iataOperatorCode=").append(iataOperatorCode);
        sb.append(", icaoOperatorCode=").append(icaoOperatorCode);
        sb.append(", description=").append(description);
        sb.append(", localDescription=").append(localDescription);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", defaultTerminal=").append(defaultTerminal);
        sb.append(", defaultTerminalMvin=").append(defaultTerminalMvin);
        sb.append(", defaultTerminalFlin=").append(defaultTerminalFlin);
        sb.append(", operatorGroups=").append(operatorGroups);
        sb.append(", airlineCategory=").append(airlineCategory);
        sb.append(", inspireTime=").append(inspireTime);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RdmsAirline)) return false;
        RdmsAirline that = (RdmsAirline) o;
        return Objects.equals(getIataOperatorCode(), that.getIataOperatorCode()) &&
                Objects.equals(getIcaoOperatorCode(), that.getIcaoOperatorCode()) &&
                Objects.equals(getDescription(), that.getDescription()) &&
                Objects.equals(getLocalDescription(), that.getLocalDescription()) &&
                Objects.equals(getCountryCode(), that.getCountryCode()) &&
                Objects.equals(getDefaultTerminal(), that.getDefaultTerminal()) &&
                Objects.equals(getDefaultTerminalMvin(), that.getDefaultTerminalMvin()) &&
                Objects.equals(getDefaultTerminalFlin(), that.getDefaultTerminalFlin()) &&
                Objects.equals(getOperatorGroups(), that.getOperatorGroups()) &&
                Objects.equals(getAirlineCategory(), that.getAirlineCategory()) &&
                Objects.equals(getInspireTime(), that.getInspireTime()) &&
                Objects.equals(getExpireTime(), that.getExpireTime());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIataOperatorCode(), getIcaoOperatorCode(), getDescription(), getLocalDescription(), getCountryCode(), getDefaultTerminal(), getDefaultTerminalMvin(), getDefaultTerminalFlin(), getOperatorGroups(), getAirlineCategory(), getInspireTime(), getExpireTime());
    }


    /***
     * Get the identity of entity.
     * @return identity of entity
     */
    @JsonIgnore
    public String getIdentity() {
        return icaoOperatorCode + inspireTime + expireTime;
    }
}