package com.unisys.aos.view.viewentity.entity.reference;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.unisys.aos.view.common.util.ThreadLocalDateUtil;
import com.unisys.aos.view.viewentity.config.ReferenceProperties;
import org.springframework.data.annotation.Transient;

import javax.annotation.Generated;
import javax.annotation.Resource;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * The <b>RdmsAirlineSubcompany</b> class is a POJO entity that represents the Airline Subcompany
 * for reference data in message.
 * It is automatically generated by MyBatisGenerator.
 * The reference data in message definition can be referred to the section 3 of
 * the document SIS_AODB_RMS.doc.
 *
 * @author Zhang Wenqiang
 * @since 2020/10/21 23:50
 */
public class RdmsAirlineSubcompany implements Serializable {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private static final long serialVersionUID = 1L;
    @Transient
    public Date parentCompanyInspire;
    @Transient
    public Date parentCompanyExpire;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String airlineIataOperatorCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String airlineSubcompanyCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String description;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String localDescription;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long parentCompanyInspireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long parentCompanyExpireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date createTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date updateTime;
    @Resource
    @Transient
    private ReferenceProperties referenceProperties;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAirlineIataOperatorCode() {
        return airlineIataOperatorCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAirlineIataOperatorCode(String airlineIataOperatorCode) {
        this.airlineIataOperatorCode = airlineIataOperatorCode == null ? null : airlineIataOperatorCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAirlineSubcompanyCode() {
        return airlineSubcompanyCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAirlineSubcompanyCode(String airlineSubcompanyCode) {
        this.airlineSubcompanyCode = airlineSubcompanyCode == null ? null : airlineSubcompanyCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDescription() {
        return description;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getLocalDescription() {
        return localDescription;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setLocalDescription(String localDescription) {
        this.localDescription = localDescription == null ? null : localDescription.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getParentCompanyInspireTime() {
        return parentCompanyInspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setParentCompanyInspireTime(Long parentCompanyInspireTime) {
        this.parentCompanyInspireTime = parentCompanyInspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getParentCompanyExpireTime() {
        return parentCompanyExpireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setParentCompanyExpireTime(Long parentCompanyExpireTime) {
        this.parentCompanyExpireTime = parentCompanyExpireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getUpdateTime() {
        return updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getParentCompanyInspire() {
        if (null == parentCompanyInspireTime) {
            parentCompanyInspire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultInspireTime());
        } else {
            parentCompanyInspire = ThreadLocalDateUtil.timestampToDate(parentCompanyInspireTime);
        }
        return parentCompanyInspire;
    }

    public Date getParentCompanyExpire() {
        if (null == parentCompanyExpireTime) {
            parentCompanyExpire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultExpireTime());
        } else {
            parentCompanyExpire = ThreadLocalDateUtil.timestampToDate(parentCompanyExpireTime);
        }
        return parentCompanyExpire;
    }

    @Override
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", airlineIataOperatorCode=").append(airlineIataOperatorCode);
        sb.append(", airlineSubcompanyCode=").append(airlineSubcompanyCode);
        sb.append(", description=").append(description);
        sb.append(", localDescription=").append(localDescription);
        sb.append(", parentCompanyInspireTime=").append(parentCompanyInspireTime);
        sb.append(", parentCompanyExpireTime=").append(parentCompanyExpireTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RdmsAirlineSubcompany)) return false;
        RdmsAirlineSubcompany that = (RdmsAirlineSubcompany) o;
        return Objects.equals(getAirlineIataOperatorCode(), that.getAirlineIataOperatorCode()) &&
                Objects.equals(getAirlineSubcompanyCode(), that.getAirlineSubcompanyCode()) &&
                Objects.equals(getDescription(), that.getDescription()) &&
                Objects.equals(getLocalDescription(), that.getLocalDescription()) &&
                Objects.equals(getParentCompanyInspireTime(), that.getParentCompanyInspireTime()) &&
                Objects.equals(getParentCompanyExpireTime(), that.getParentCompanyExpireTime());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAirlineIataOperatorCode(), getAirlineSubcompanyCode(), getDescription(), getLocalDescription(), getParentCompanyInspireTime(), getParentCompanyExpireTime());
    }


    /***
     * Get the identity of entity.
     * @return identity of entity
     */
    @JsonIgnore
    public String getIdentity() {
        return airlineIataOperatorCode + parentCompanyInspireTime + parentCompanyExpireTime;
    }
}