package com.unisys.aos.view.viewentity.entity.reference;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.unisys.aos.view.common.util.ThreadLocalDateUtil;
import com.unisys.aos.view.viewentity.config.ReferenceProperties;
import org.springframework.data.annotation.Transient;

import javax.annotation.Generated;
import javax.annotation.Resource;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * The <b>RdmsRegistration</b> class is a POJO entity that represents the Registration Code
 * for reference data in message.
 * It is automatically generated by MyBatisGenerator.
 * The reference data in message definition can be referred to the section 3 of
 * the document SIS_AODB_RMS.doc.
 *
 * @author Zhang Wenqiang
 * @since 2020/10/21 23:50
 */
public class RdmsRegistration implements Serializable {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private static final long serialVersionUID = 1L;
    @Transient
    public Date inspire;
    @Transient
    public Date expire;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String registrationCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String aircraftTypeCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Integer organizationId;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String airlineCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String airlineSubcompanyCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Short maxPax;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal maxFreightWeight;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal maxTakeoffWeight;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long inspireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long expireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date createTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date updateTime;
    @Resource
    @Transient
    private ReferenceProperties referenceProperties;

    public Date getInspire() {
        if (null == inspireTime) {
            inspire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultInspireTime());
        } else {
            inspire = ThreadLocalDateUtil.timestampToDate(inspireTime);
        }
        return inspire;
    }

    public Date getExpire() {
        if (null == expireTime) {
            expire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultExpireTime());
        } else {
            expire = ThreadLocalDateUtil.timestampToDate(expireTime);
        }
        return expire;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getRegistrationCode() {
        return registrationCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setRegistrationCode(String registrationCode) {
        this.registrationCode = registrationCode == null ? null : registrationCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAircraftTypeCode() {
        return aircraftTypeCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAircraftTypeCode(String aircraftTypeCode) {
        this.aircraftTypeCode = aircraftTypeCode == null ? null : aircraftTypeCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Integer getOrganizationId() {
        return organizationId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAirlineCode() {
        return airlineCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAirlineCode(String airlineCode) {
        this.airlineCode = airlineCode == null ? null : airlineCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getAirlineSubcompanyCode() {
        return airlineSubcompanyCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAirlineSubcompanyCode(String airlineSubcompanyCode) {
        this.airlineSubcompanyCode = airlineSubcompanyCode == null ? null : airlineSubcompanyCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Short getMaxPax() {
        return maxPax;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxPax(Short maxPax) {
        this.maxPax = maxPax;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getMaxFreightWeight() {
        return maxFreightWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxFreightWeight(BigDecimal maxFreightWeight) {
        this.maxFreightWeight = maxFreightWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getMaxTakeoffWeight() {
        return maxTakeoffWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxTakeoffWeight(BigDecimal maxTakeoffWeight) {
        this.maxTakeoffWeight = maxTakeoffWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getInspireTime() {
        return inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setInspireTime(Long inspireTime) {
        this.inspireTime = inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getExpireTime() {
        return expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getUpdateTime() {
        return updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", registrationCode=").append(registrationCode);
        sb.append(", aircraftTypeCode=").append(aircraftTypeCode);
        sb.append(", organizationId=").append(organizationId);
        sb.append(", airlineCode=").append(airlineCode);
        sb.append(", airlineSubcompanyCode=").append(airlineSubcompanyCode);
        sb.append(", maxPax=").append(maxPax);
        sb.append(", maxFreightWeight=").append(maxFreightWeight);
        sb.append(", maxTakeoffWeight=").append(maxTakeoffWeight);
        sb.append(", inspireTime=").append(inspireTime);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RdmsRegistration)) return false;
        RdmsRegistration that = (RdmsRegistration) o;
        return Objects.equals(getRegistrationCode(), that.getRegistrationCode()) &&
                Objects.equals(getAircraftTypeCode(), that.getAircraftTypeCode()) &&
                Objects.equals(getOrganizationId(), that.getOrganizationId()) &&
                Objects.equals(getAirlineCode(), that.getAirlineCode()) &&
                Objects.equals(getAirlineSubcompanyCode(), that.getAirlineSubcompanyCode()) &&
                Objects.equals(getMaxPax(), that.getMaxPax()) &&
                Objects.equals(getMaxFreightWeight(), that.getMaxFreightWeight()) &&
                Objects.equals(getMaxTakeoffWeight(), that.getMaxTakeoffWeight()) &&
                Objects.equals(getInspireTime(), that.getInspireTime()) &&
                Objects.equals(getExpireTime(), that.getExpireTime());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRegistrationCode(), getAircraftTypeCode(), getOrganizationId(), getAirlineCode(), getAirlineSubcompanyCode(), getMaxPax(), getMaxFreightWeight(), getMaxTakeoffWeight(), getInspireTime(), getExpireTime());
    }


    /***
     * Get the identity of entity.
     * @return identity of entity
     */
    @JsonIgnore
    public String getIdentity() {
        return registrationCode + inspireTime + expireTime;
    }
}