package com.unisys.aos.view.viewentity.entity.reference;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.unisys.aos.view.common.util.ThreadLocalDateUtil;
import com.unisys.aos.view.viewentity.config.ReferenceProperties;
import org.springframework.data.annotation.Transient;

import javax.annotation.Generated;
import javax.annotation.Resource;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * The <b>RdmsAircraftType</b> class is a POJO entity that represents the Aircraft Type
 * for reference data in message.
 * It is automatically generated by MyBatisGenerator.
 * The reference data in message definition can be referred to the section 3 of
 * the document SIS_AODB_RMS.doc.
 *
 * @author Zhang Wenqiang
 * @since 2020/10/21 23:50
 */
public class RdmsAircraftType implements Serializable {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private static final long serialVersionUID = 1L;
    @Transient
    public Date inspire;
    @Transient
    public Date expire;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String iataCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String icaoCode;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String description;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String localDescription;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String sizeCategory;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Short maxPax;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal maxFreightWeight;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal maxTakeoffWeight;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal aircraftLength;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal wingSpan;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private BigDecimal minHandlingTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Byte maxAirbridge;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long inspireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long expireTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date createTime;
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Date updateTime;
    @Resource
    @Transient
    private ReferenceProperties referenceProperties;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getIataCode() {
        return iataCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIataCode(String iataCode) {
        this.iataCode = iataCode == null ? null : iataCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getIcaoCode() {
        return icaoCode;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIcaoCode(String icaoCode) {
        this.icaoCode = icaoCode == null ? null : icaoCode.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getDescription() {
        return description;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getLocalDescription() {
        return localDescription;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setLocalDescription(String localDescription) {
        this.localDescription = localDescription == null ? null : localDescription.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getSizeCategory() {
        return sizeCategory;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setSizeCategory(String sizeCategory) {
        this.sizeCategory = sizeCategory == null ? null : sizeCategory.trim();
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Short getMaxPax() {
        return maxPax;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxPax(Short maxPax) {
        this.maxPax = maxPax;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getMaxFreightWeight() {
        return maxFreightWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxFreightWeight(BigDecimal maxFreightWeight) {
        this.maxFreightWeight = maxFreightWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getMaxTakeoffWeight() {
        return maxTakeoffWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxTakeoffWeight(BigDecimal maxTakeoffWeight) {
        this.maxTakeoffWeight = maxTakeoffWeight;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getAircraftLength() {
        return aircraftLength;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setAircraftLength(BigDecimal aircraftLength) {
        this.aircraftLength = aircraftLength;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getWingSpan() {
        return wingSpan;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setWingSpan(BigDecimal wingSpan) {
        this.wingSpan = wingSpan;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public BigDecimal getMinHandlingTime() {
        return minHandlingTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMinHandlingTime(BigDecimal minHandlingTime) {
        this.minHandlingTime = minHandlingTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Byte getMaxAirbridge() {
        return maxAirbridge;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setMaxAirbridge(Byte maxAirbridge) {
        this.maxAirbridge = maxAirbridge;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getInspireTime() {
        return inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setInspireTime(Long inspireTime) {
        this.inspireTime = inspireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getExpireTime() {
        return expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setExpireTime(Long expireTime) {
        this.expireTime = expireTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Date getUpdateTime() {
        return updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getInspire() {
        if (null == inspireTime) {
            inspire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultInspireTime());
        } else {
            inspire = ThreadLocalDateUtil.timestampToDate(inspireTime);
        }
        return inspire;
    }

    public Date getExpire() {
        if (null == expireTime) {
            expire = ThreadLocalDateUtil.timestampToDate(referenceProperties.getDefaultExpireTime());
        } else {
            expire = ThreadLocalDateUtil.timestampToDate(expireTime);
        }
        return expire;
    }

    @Override
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", iataCode=").append(iataCode);
        sb.append(", icaoCode=").append(icaoCode);
        sb.append(", description=").append(description);
        sb.append(", localDescription=").append(localDescription);
        sb.append(", sizeCategory=").append(sizeCategory);
        sb.append(", maxPax=").append(maxPax);
        sb.append(", maxFreightWeight=").append(maxFreightWeight);
        sb.append(", maxTakeoffWeight=").append(maxTakeoffWeight);
        sb.append(", aircraftLength=").append(aircraftLength);
        sb.append(", wingSpan=").append(wingSpan);
        sb.append(", minHandlingTime=").append(minHandlingTime);
        sb.append(", maxAirbridge=").append(maxAirbridge);
        sb.append(", inspireTime=").append(inspireTime);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RdmsAircraftType)) return false;
        RdmsAircraftType that = (RdmsAircraftType) o;
        return Objects.equals(getIataCode(), that.getIataCode()) &&
                Objects.equals(getIcaoCode(), that.getIcaoCode()) &&
                Objects.equals(getDescription(), that.getDescription()) &&
                Objects.equals(getLocalDescription(), that.getLocalDescription()) &&
                Objects.equals(getSizeCategory(), that.getSizeCategory()) &&
                Objects.equals(getMaxPax(), that.getMaxPax()) &&
                Objects.equals(getMaxFreightWeight(), that.getMaxFreightWeight()) &&
                Objects.equals(getMaxTakeoffWeight(), that.getMaxTakeoffWeight()) &&
                Objects.equals(getAircraftLength(), that.getAircraftLength()) &&
                Objects.equals(getWingSpan(), that.getWingSpan()) &&
                Objects.equals(getMinHandlingTime(), that.getMinHandlingTime()) &&
                Objects.equals(getMaxAirbridge(), that.getMaxAirbridge()) &&
                Objects.equals(getInspireTime(), that.getInspireTime()) &&
                Objects.equals(getExpireTime(), that.getExpireTime());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIataCode(), getIcaoCode(), getDescription(), getLocalDescription(), getSizeCategory(), getMaxPax(), getMaxFreightWeight(), getMaxTakeoffWeight(), getAircraftLength(), getWingSpan(), getMinHandlingTime(), getMaxAirbridge(), getInspireTime(), getExpireTime());
    }


    /***
     * Get the identity of entity.
     * @return identity of entity
     */
    @JsonIgnore
    public String getIdentity() {
        return iataCode + inspireTime + expireTime;
    }
}