server:
  port: 8081
spring:
  application:
    name: view-portal
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/view?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Best9Luck!
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
  redis:
    host: localhost
    port: 7963
    password: Best9Luck!
    subscribe:
      topic:
  couchbase:
    env:
      timeouts:
        view:
logging:
  level:
    root: info
    com.unisys.aos.view: debug
  file:
    max-history: 30
    max-size: 10MB
    name: ./logs/view-portal.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID:- } --- [%thread] %-45.45logger{44} : %msg%n"
    rolling-file-name: view-portal.%d{yyyy-MM-dd}-%i.gz
management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  enabled: true
  secret: Rum%>J]_@!DzALL0no3)^.0d
  accessTokenExpiration: 3000000
  refreshTokenExpiration: 86400000
  header: Authorization
  usernameHeader: UserId
  useDefaultController: true
  permitLoginUserURI:
    - /view/refresh-token
    - /view/logout
    - /view/logout-test
    - /view/admin/permit-all/functions
    - /view/admin/permit-all/user-setting
  permitAllURI:
    - /view/websocket/FLOP
    - /view/login-test
  test-token: WishAllTheBest!
flight:
  home-airport: CTU

